# Generated by Django 4.1 on 2022-10-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_is_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture_height',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture_width',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='media/profiles/'),
        ),
    ]
