# Generated by Django 4.1 on 2022-10-01 01:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=50)),
                ('place_direction', models.CharField(max_length=50)),
                ('place_phone_number', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?57?\\d{8,15}$')])),
                ('place_opening_hours', models.CharField(max_length=50)),
                ('place_visit_date', models.DateField(blank=True, null=True)),
                ('place_logo', models.ImageField(blank=True, default='media/places/logo/default.jpg', null=True, upload_to='media/places/logo')),
                ('place_photo', models.ImageField(blank=True, default='media/places/photo/default.jpg', null=True, upload_to='media/places/photo')),
                ('place_logo_height', models.PositiveIntegerField(blank=True, default='40', editable=False, null=True)),
                ('place_logo_width', models.PositiveIntegerField(blank=True, default='40', editable=False, null=True)),
                ('place_photo_height', models.PositiveIntegerField(blank=True, default='200', editable=False, null=True)),
                ('place_photo_width', models.PositiveIntegerField(blank=True, default='200', editable=False, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
