# Generated by Django 4.1 on 2022-10-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='place_direction',
            new_name='direction',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='place_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='place_logo_height',
            new_name='logo_height',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='place_logo_width',
            new_name='logo_width',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='place_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='place_opening_hours',
            new_name='opening_hours',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='place_phone_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='place_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='place_visit_date',
            new_name='visit_date',
        ),
        migrations.RemoveField(
            model_name='place',
            name='place_photo_height',
        ),
        migrations.RemoveField(
            model_name='place',
            name='place_photo_width',
        ),
        migrations.AddField(
            model_name='place',
            name='photo_height',
            field=models.PositiveIntegerField(blank=True, default='324', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='photo_width',
            field=models.PositiveIntegerField(blank=True, default='422', editable=False, null=True),
        ),
    ]
