# Generated by Django 4.1 on 2022-10-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_rename_place_direction_place_direction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='logo_height',
        ),
        migrations.RemoveField(
            model_name='place',
            name='logo_width',
        ),
        migrations.RemoveField(
            model_name='place',
            name='photo_height',
        ),
        migrations.RemoveField(
            model_name='place',
            name='photo_width',
        ),
        migrations.AlterField(
            model_name='place',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media/places/logo'),
        ),
        migrations.AlterField(
            model_name='place',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/places/photo'),
        ),
    ]
